### ISSUE TITLE
Elevated API error rate

### ISSUE THREAD

**Issue by Kagaherk** [luzmo-official/cumul.io-status#3]
We're currently seeing an increased number of 502 errors and slowed down API responses on the https://api.cumul.io route. We're investigating the root cause of this problem and are trying to restore service as soon as possible.

Update 18:21 CET
The average & p95 API call duration have now significantly decreased and are again under our target thresholds. We still see occasional 502 errors and are further investigating the root cause of this problem.

Update 21:25 CET
We've been monitoring the situation for a while and metrics are back at normal levels. This issue was likely caused by a networking configuration issue on an application server that caused frequent TCP connection resets when under high throughput (in terms of bandwidth required vs. the more common case of high numbers of connections). This bandwidth spike was in turn caused by a public/press release by a customer.

We will further monitor the configuration changes made and will look into other improvements. We're closing the active incident as we do not expect this issue to re-surface.

**Comment by vyrwu** [comment]
When can we expect a resolution?

**Comment by Kagaherk** [comment]
Update 18:21 CET
The average & p95 API call duration have now significantly decreased and are again under our target thresholds. We still see occasional 502 errors and are further investigating the root cause of this problem.

**Comment by b12e** [comment]
@Kagaherk is there any further news on root cause - or can we expect "normal" operations even though the incident is still open on your end and no relapse? 

I know it's Thuis / Familie time, no stress ;)

**Comment by Kagaherk** [comment]
Update 21:25 CET
We've been monitoring the situation for a while and metrics are back at normal levels. This issue was likely caused by a networking configuration issue on an application server that caused frequent TCP connection resets when under high throughput (in terms of bandwidth required vs. the more common case of high numbers of connections). This bandwidth spike was in turn caused by a public/press release by a customer.

We will further monitor the configuration changes made and will look into other improvements. We're closing the active incident as we do not expect this issue to re-surface.
